### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by minhaj-313**
I add 2 facts in this repository if you like this then please merge my PR by labeling as hacktoberfest-accepted. If it is not proper then you suggest me. Thank you sir.

### CODE REVIEW

**Comment by zabihhaqqani** [comment]
I might count as spam in hactoberfest.

**Comment by minhaj-313** [comment]
> I might count as spam in hactoberfest.

please don't do that please sir

**Comment by zabihhaqqani** [comment]
try working on #18

**Comment by minhaj-313** [comment]
> try working on #18

ok sir, please don't do spam to me please

**Comment by zabihhaqqani** [comment]
sure I wont

**Comment by zabihhaqqani** [comment]
create an issue first then send a pull request to avoid confusion

**Comment by minhaj-313** [comment]
> create an issue first then send a pull request to avoid confusion

Ok sir, I am new to this things so please guide me if I doing wrong but I will try my best

**Pull request closed without merging**
